version: '3'
services:
  playground_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - playground_db
    environment:
      - DB_HOST=db
      - DB_PORT=5432

  playground_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: